name: go-snapctl-tester
base: core24
version: test
summary: Tester for go-snapctl
description: This snap is used to run the tests inside the snap environment.

grade: devel
confinement: strict

plugs:
  # Plug for testing snapctl commands
  test-plug:
    interface: content
    target: $SNAP_DATA
  
  home:
    read: all # to access tests located in some home directory with root user

apps:
  # App for running the tests
  test:
    command: bin/test.sh
    plugs: [network, home]

  # Mocked apps needed for testing
  mock-service: &ms
    command: bin/mock-app.sh
    daemon: simple
    install-mode: disable
  mock-service-2: *ms

parts:
  go:
    ## Using stage go snap doesn't work,
    ## resulting in core dump when running go:
    # plugin: nil
    # stage-snaps:
    #   - go/1.17
    # organize:
    #   '*': go/
    plugin: dump
    source: https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
    organize:
      "*": go/

  bin:
    plugin: dump
    source: snap/local
